Repository PeopleForBikes/svggloo, pull requests merged in 2022-08, with the labels that each got.

#4 Fix score alignments
  examples/brochure/brochure.svg
Labels: size/XL

#5 Make it BNA Mechanics compliant
  .editorconfig
  .github/README.md
  .github/dependabot.yml
  .markdownlint.yml
  .prettierignore
  LICENSE
  README.md
  code-of-conduct.md
  justfile
Labels: size/M

#12 Fix branch protection mess
  Cargo.lock
  Cargo.toml
Labels: size/XS

#13 Improve batch conversion with Inkscape
  src/template.rs
Labels: size/L

#14 Add CairoSVG Exporter
  examples/brochure/main.rs
  examples/quantifier/main.rs
  src/cli.rs
  src/main.rs
  src/template.rs
Labels: size/L

#17 Add docstrings and tests
  examples/brochure/main.rs
  src/template.rs
Labels: size/M
